# DNS Providers Configuration

[providers]

[providers.alidns-doh]
addr = "223.5.5.5:443"
hostname = "dns.alidns.com"

[providers.dnspod-doh]
addr = "1.12.12.12:443"
hostname = "doh.pub"

# Uncomment below to enable more providers
# [providers.cloudflare-doh]
# addr = "1.1.1.1:443"
# hostname = "1.1.1.1"

# [providers.google-doh]
# addr = "8.8.8.8:443"
# hostname = "dns.google"
