# DNS Providers Configuration
[providers]

[providers.alidns-doh]
addr = "223.5.5.5:443"
hostname = "dns.alidns.com"
domain_groups = ["default"]

[providers.dnspod-doh]
addr = "1.12.12.12:443"
hostname = "doh.pub"
domain_groups = ["default"]

[providers.google-doh]
addr = "8.8.8.8:443"
hostname = "dns.google"
domain_groups = ["google", "google_exclude", "social"]

[providers.cloudflare-doh]
addr = "1.1.1.1:443"
hostname = "1.1.1.1"
domain_groups = ["google", "google_exclude", "social"]

# Domain Groups Configuration
[domain_groups]
default = [] # All domains

google = ["google.com", "google.com.hk", "googleapis.com", "youtube.com"]

google_exclude = ["!safebrowsing.googleapis.com"]

social = ["facebook.com", "x.com", "instagram.com", "twitter.com", "github.com"]
